### obtener todos los registros de PlayerPerformance
GET http://127.0.0.1:3000/api/player-performances

### obtener un registro de PlayerPerformance por id
GET http://127.0.0.1:3000/api/player-performances/1

### crear un nuevo registro de PlayerPerformance
POST http://127.0.0.1:3000/api/player-performances
Content-Type: application/json

{
  "realPlayerId": "1",
  "matchdayId": "1",
  "leagueId": "1",
  "matchId": "1",
  "pointsObtained": 12
}

### actualizar un registro de PlayerPerformance por id
PUT http://127.0.0.1:3000/api/player-performances/1
Content-Type: application/json

{
  "realPlayerId": "1",
  "matchdayId": "1",
  "leagueId": "1",
  "matchId": "1",
  "pointsObtained": 112
}

### actualizar parcialmente un registro de PlayerPerformance por id
PATCH http://127.0.0.1:3000/api/player-performances/1
Content-Type: application/json

{
  "realPlayerId": "1",
  "matchdayId": "1",
  "leagueId": "1",
  "matchId": "1",
  "pointsObtained": 112
}

### eliminar un registro de PlayerPerformance por id
DELETE http://127.0.0.1:3000/api/player-performances/1
