### obtener todos los registros de Tournament
GET http://127.0.0.1:3000/api/tournaments

### obtener un registro de Tournament por id
GET http://127.0.0.1:3000/api/tournaments/1

### crear un nuevo registro de Tournament
POST http://127.0.0.1:3000/api/tournaments
Content-Type: application/json

{
  "name": "Liga Profesional",
  "leagueId": "1",
  "sport": "Football",
  "creationDate": "2026-02-10T12:00:00.000Z",
  "initialBudget": 60000000,
  "squadSize": 16,
  "status": "active",
  "clauseWaitDays": 14,
  "creatorUserId": 1
}

### actualizar un registro de Tournament por id
PUT http://127.0.0.1:3000/api/tournaments/1
Content-Type: application/json

{
  "name": "Liga Profesional actualizado",
  "leagueId": "1",
  "initialBudget": 60000100,
  "squadSize": 125,
  "status": "inactive",
  "clauseEnableDate": "2026-02-20T12:00:00.000Z"
}

### actualizar parcialmente un registro de Tournament por id
PATCH http://127.0.0.1:3000/api/tournaments/1
Content-Type: application/json

{
  "name": "Liga Profesional actualizado",
  "leagueId": "1",
  "status": "inactive"
}

### eliminar un registro de Tournament por id
DELETE http://127.0.0.1:3000/api/tournaments/1


### Nota: publicCode se genera automáticamente al crear torneo (único)


### sumar puntos de fin de fecha por league/matchday (opcional match)
POST http://127.0.0.1:3000/api/tournaments/sum-end-of-matchday-points
Content-Type: application/json

{
  "leagueId": 1,
  "matchdayNumber": 1,
  "matchId": 1
}
