### obtener todos los registros de Tournament
GET http://127.0.0.1:3000/api/tournaments

### obtener un registro de Tournament por id
GET http://127.0.0.1:3000/api/tournaments/550e8400-e29b-41d4-a716-446655440000

### crear un nuevo registro de Tournament
POST http://127.0.0.1:3000/api/tournaments
Content-Type: application/json

{
  "name": "Liga Profesional",
  "leagueId": "550e8400-e29b-41d4-a716-446655440000",
  "initialBudget": 60000000,
  "squadSize": 25,
  "status": "active",
  "clauseEnableDate": "2026-02-20T12:00:00.000Z"
}

### actualizar un registro de Tournament por id
PUT http://127.0.0.1:3000/api/tournaments/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "name": "Liga Profesional actualizado",
  "leagueId": "550e8400-e29b-41d4-a716-446655440000",
  "initialBudget": 60000100,
  "squadSize": 125,
  "status": "active actualizado",
  "clauseEnableDate": "2026-02-20T12:00:00.000Z"
}

### actualizar parcialmente un registro de Tournament por id
PATCH http://127.0.0.1:3000/api/tournaments/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "name": "Liga Profesional actualizado",
  "leagueId": "550e8400-e29b-41d4-a716-446655440000",
  "status": "active actualizado"
}

### eliminar un registro de Tournament por id
DELETE http://127.0.0.1:3000/api/tournaments/550e8400-e29b-41d4-a716-446655440000
