### obtener todos los registros de Match
GET http://127.0.0.1:3000/api/matches

### obtener un registro de Match por id
GET http://127.0.0.1:3000/api/matches/1

### crear un nuevo registro de Match
POST http://127.0.0.1:3000/api/matches
Content-Type: application/json

{
  "matchdayId": "1",
  "externalApiId": "1",
  "matchdayId": "1",
  "externalApiId": "2",
  "homeTeam": "River Plate",
  "awayTeam": "Boca Juniors",
  "startDateTime": "2026-02-15T18:00:00.000Z",
  "status": "active"
}

### actualizar un registro de Match por id
PUT http://127.0.0.1:3000/api/matches/1
PUT http://127.0.0.1:3000/api/matches/3
Content-Type: application/json

{
  "matchdayId": "1",
  "externalApiId": "1",
  "matchdayId": "3",
  "externalApiId": "2",
  "homeTeam": "River Plate actualizado",
  "awayTeam": "Boca Juniors actualizado",
  "startDateTime": "2026-02-15T18:00:00.000Z",
  "status": "active actualizado"
}

### actualizar parcialmente un registro de Match por id
PATCH http://127.0.0.1:3000/api/matches/1
Content-Type: application/json

{
  "matchdayId": "1",
  "externalApiId": "1",
  "homeTeam": "River Plate actualizado",
  "status": "active actualizado"
}

### eliminar un registro de Match por id
DELETE http://127.0.0.1:3000/api/matches/1
