### SportsApiPro - player by playerId
GET http://127.0.0.1:3000/api/external/sportsapipro/player?playerId=123

### SportsApiPro - all players by teamId
GET http://127.0.0.1:3000/api/external/sportsapipro/team-players?teamId=8650

### SportsApiPro - allowed leagues (47,112,87,55,53,54)
GET http://127.0.0.1:3000/api/external/sportsapipro/leagues

### SportsApiPro - teams by leagueId
GET http://127.0.0.1:3000/api/external/sportsapipro/teams?leagueId=112

### SportsApiPro - team detail by teamId
GET http://127.0.0.1:3000/api/external/sportsapipro/team-detail?teamId=8650
