### obtener todos los registros de ParticipantMatchdayPoints
GET http://127.0.0.1:3000/api/participant-matchday-points

### obtener un registro de ParticipantMatchdayPoints por id
GET http://127.0.0.1:3000/api/participant-matchday-points/1

### crear un nuevo registro de ParticipantMatchdayPoints
POST http://127.0.0.1:3000/api/participant-matchday-points
Content-Type: application/json

{
  "participantId": "1",
  "matchdayId": "1",
  "matchdayPoints": 63,
  "accumulatedPoints": 302,
  "position": "DEL",
  "calculationDate": "2026-02-10T12:00:00.000Z"
}

### actualizar un registro de ParticipantMatchdayPoints por id
PUT http://127.0.0.1:3000/api/participant-matchday-points/1
Content-Type: application/json

{
  "participantId": "1",
  "matchdayId": "1",
  "matchdayPoints": 163,
  "accumulatedPoints": 402,
  "position": "DEL",
  "calculationDate": "2026-02-10T12:00:00.000Z"
}

### actualizar parcialmente un registro de ParticipantMatchdayPoints por id
PATCH http://127.0.0.1:3000/api/participant-matchday-points/1
Content-Type: application/json

{
  "participantId": "1",
  "matchdayId": "1",
  "matchdayPoints": 163
}

### eliminar un registro de ParticipantMatchdayPoints por id
DELETE http://127.0.0.1:3000/api/participant-matchday-points/1
