### obtener todos los registros de GameMatch
GET http://127.0.0.1:3000/api/matches

### obtener un registro de GameMatch por id
GET http://127.0.0.1:3000/api/matches/1

### crear un nuevo registro de GameMatch
POST http://127.0.0.1:3000/api/matches
Content-Type: application/json

{
  "matchdayId": "1",
  "leagueId": "1",
  "externalApiId": "2",
  "homeTeam": "River Plate",
  "awayTeam": "Boca Juniors",
  "startDateTime": "2026-02-15T18:00:00.000Z",
  "status": "scheduled"
}

### actualizar un registro de GameMatch por id
PUT http://127.0.0.1:3000/api/matches/1
Content-Type: application/json

{
  "matchdayId": "3",
  "leagueId": "1",
  "externalApiId": "2",
  "homeTeam": "River Plate actualizado",
  "awayTeam": "Boca Juniors actualizado",
  "startDateTime": "2026-02-15T18:00:00.000Z",
  "status": "finalizado"
}

### actualizar parcialmente un registro de GameMatch por id
PATCH http://127.0.0.1:3000/api/matches/1
Content-Type: application/json

{
  "leagueId": "1",
  "homeTeam": "River Plate actualizado",
  "status": "finalizado"
}

### eliminar un registro de GameMatch por id
DELETE http://127.0.0.1:3000/api/matches/1
