### obtener todos los registros de Shielding
GET http://localhost:3000/api/shieldings

### obtener un registro de Shielding por id
GET http://localhost:3000/api/shieldings/550e8400-e29b-41d4-a716-446655440000

### crear un nuevo registro de Shielding
POST http://localhost:3000/api/shieldings
Content-Type: application/json

{
  "name": "sample"
}

### actualizar un registro de Shielding por id
PUT http://localhost:3000/api/shieldings/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "name": "updated sample"
}

### eliminar un registro de Shielding por id
DELETE http://localhost:3000/api/shieldings/550e8400-e29b-41d4-a716-446655440000
