### obtener todos los registros de Participant
GET http://127.0.0.1:3000/api/participants

### obtener un registro de Participant por id
GET http://127.0.0.1:3000/api/participants/1

### crear un nuevo registro de Participant
POST http://127.0.0.1:3000/api/participants
Content-Type: application/json

{
  "userId": "1",
  "tournamentId": "1",
  "bankBudget": 50000000,
  "reservedMoney": 7000000,
  "availableMoney": 43000000,
  "totalScore": 124
}

### actualizar un registro de Participant por id
PUT http://127.0.0.1:3000/api/participants/1
Content-Type: application/json

{
  "userId": "1",
  "tournamentId": "1",
  "bankBudget": 50000100,
  "reservedMoney": 7000100,
  "availableMoney": 43000100,
  "totalScore": 224
}

### actualizar parcialmente un registro de Participant por id
PATCH http://127.0.0.1:3000/api/participants/1
Content-Type: application/json

{
  "userId": "1",
  "tournamentId": "1",
  "bankBudget": 50000100
}

### eliminar un registro de Participant por id
DELETE http://127.0.0.1:3000/api/participants/1

### unirse a torneo por codigo
POST http://127.0.0.1:3000/api/participants/join-by-code
Content-Type: application/json

{
  "userId": 1,
  "tournamentCode": "T-ABCDEFGH"
}

### salir de torneo y eliminar participant + relacionados
POST http://127.0.0.1:3000/api/participants/leave-tournament
Content-Type: application/json

{
  "userId": 1,
  "tournamentId": 1
}
