### obtener todos los registros de PlayerPointsBreakdown
GET http://127.0.0.1:3000/api/player-points-breakdowns

### obtener un registro de PlayerPointsBreakdown por id
GET http://127.0.0.1:3000/api/player-points-breakdowns/1

### crear un nuevo registro de PlayerPointsBreakdown
POST http://127.0.0.1:3000/api/player-points-breakdowns
Content-Type: application/json

{
  "participantId": "1",
  "matchdayId": "1",
  "realPlayerId": "1",
  "contributedPoints": 9,
  "playerPerformanceId": "1"
}

### actualizar un registro de PlayerPointsBreakdown por id
PUT http://127.0.0.1:3000/api/player-points-breakdowns/1
Content-Type: application/json

{
  "participantId": "1",
  "matchdayId": "1",
  "realPlayerId": "1",
  "contributedPoints": 109,
  "playerPerformanceId": "1"
}

### actualizar parcialmente un registro de PlayerPointsBreakdown por id
PATCH http://127.0.0.1:3000/api/player-points-breakdowns/1
Content-Type: application/json

{
  "participantId": "1",
  "matchdayId": "1",
  "realPlayerId": "1"
}

### eliminar un registro de PlayerPointsBreakdown por id
DELETE http://127.0.0.1:3000/api/player-points-breakdowns/1
