### obtener todos los registros de RealTeam
GET http://localhost:3000/api/real-teams

### obtener un registro de RealTeam por id
GET http://localhost:3000/api/real-teams/550e8400-e29b-41d4-a716-446655440000

### crear un nuevo registro de RealTeam
POST http://localhost:3000/api/real-teams
Content-Type: application/json

{
  "name": "sample"
}

### actualizar un registro de RealTeam por id
PUT http://localhost:3000/api/real-teams/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
  "name": "updated sample"
}

### eliminar un registro de RealTeam por id
DELETE http://localhost:3000/api/real-teams/550e8400-e29b-41d4-a716-446655440000
