### obtener todos los registros de RealTeam
GET http://127.0.0.1:3000/api/real-teams

### obtener un registro de RealTeam por id
GET http://127.0.0.1:3000/api/real-teams/1

### crear un nuevo registro de RealTeam
POST http://127.0.0.1:3000/api/real-teams
Content-Type: application/json

{
  "name": "Liga Profesional",
  "leagueId": "1",
  "idEnApi": "1"
}

### actualizar un registro de RealTeam por id
PUT http://127.0.0.1:3000/api/real-teams/1
Content-Type: application/json

{
  "name": "Liga Profesional actualizado",
  "leagueId": "1",
  "idEnApi": "1"
}

### actualizar parcialmente un registro de RealTeam por id
PATCH http://127.0.0.1:3000/api/real-teams/1
Content-Type: application/json

{
  "name": "Liga Profesional actualizado",
  "leagueId": "1",
  "idEnApi": "1"
}

### eliminar un registro de RealTeam por id
DELETE http://127.0.0.1:3000/api/real-teams/1
