### obtener todos los registros de Matchday
GET http://127.0.0.1:3000/api/matchdays

### obtener un registro de Matchday por id
GET http://127.0.0.1:3000/api/matchdays/1

### crear un nuevo registro de Matchday
POST http://127.0.0.1:3000/api/matchdays
Content-Type: application/json

{
  "leagueId": "1",
  "season": "2025/2026",
  "matchdayNumber": 3,
  "startDate": "2026-02-15T18:00:00.000Z",
  "endDate": "2026-02-15T20:00:00.000Z",
  "status": "active"
}

### actualizar un registro de Matchday por id
PUT http://127.0.0.1:3000/api/matchdays/1
Content-Type: application/json

{
  "leagueId": "1",
  "season": "2025/2026 actualizado",
  "matchdayNumber": 103,
  "startDate": "2026-02-15T18:00:00.000Z",
  "endDate": "2026-02-15T20:00:00.000Z",
  "status": "active actualizado"
}

### actualizar parcialmente un registro de Matchday por id
PATCH http://127.0.0.1:3000/api/matchdays/1
Content-Type: application/json

{
  "leagueId": "1",
  "season": "2025/2026 actualizado",
  "matchdayNumber": 103,
  "status": "active actualizado"
}

### eliminar un registro de Matchday por id
DELETE http://127.0.0.1:3000/api/matchdays/1
