### obtener todos los registros de ParticipantSquad
GET http://127.0.0.1:3000/api/participant-squads

### obtener un registro de ParticipantSquad por id
GET http://127.0.0.1:3000/api/participant-squads/1

### crear un nuevo registro de ParticipantSquad
POST http://127.0.0.1:3000/api/participant-squads
Content-Type: application/json

{
  "participantId": "1",
  "startingRealPlayersIds": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  "substitutesRealPlayersIds": [12, 13],
  "formation": "4-4-2",
  "releaseDate": "2026-02-20T12:00:00.000Z",
  "purchasePrice": 2100000,
  "acquisitionType": "bid_purchase"
}

### actualizar un registro de ParticipantSquad por id
PUT http://127.0.0.1:3000/api/participant-squads/1
Content-Type: application/json

{
  "participantId": "1",
  "startingRealPlayersIds": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  "substitutesRealPlayersIds": [14, 15],
  "formation": "4-3-3",
  "releaseDate": "2026-02-20T12:00:00.000Z",
  "purchasePrice": 2100100,
  "acquisitionType": "admin_assignment"
}

### actualizar parcialmente un registro de ParticipantSquad por id
PATCH http://127.0.0.1:3000/api/participant-squads/1
Content-Type: application/json

{
  "startingRealPlayersIds": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  "substitutesRealPlayersIds": [12, 13, 14]
}

### eliminar un registro de ParticipantSquad por id
DELETE http://127.0.0.1:3000/api/participant-squads/1
