### obtener todos los registros de MatchdayMarket
GET http://127.0.0.1:3000/api/matchday-markets

### obtener un registro de MatchdayMarket por id
GET http://127.0.0.1:3000/api/matchday-markets/1

### crear un nuevo registro de MatchdayMarket
POST http://127.0.0.1:3000/api/matchday-markets
Content-Type: application/json

{
  "tournamentId": "1",
  "matchdayId": "1",
  "dependantPlayerId": "1",
  "minimumPrice": 1800000,
  "origin": "system_initial_market",
  "sellerParticipantId": "1"
}

### actualizar un registro de MatchdayMarket por id
PUT http://127.0.0.1:3000/api/matchday-markets/1
Content-Type: application/json

{
  "tournamentId": "1",
  "matchdayId": "1",
  "dependantPlayerId": "1",
  "minimumPrice": 1800100,
  "origin": "participant_sale",
  "sellerParticipantId": "1"
}

### actualizar parcialmente un registro de MatchdayMarket por id
PATCH http://127.0.0.1:3000/api/matchday-markets/1
Content-Type: application/json

{
  "tournamentId": "1",
  "matchdayId": "1",
  "dependantPlayerId": "1"
}

### eliminar un registro de MatchdayMarket por id
DELETE http://127.0.0.1:3000/api/matchday-markets/1
