### obtener todos los registros de RealPlayer
GET http://127.0.0.1:3000/api/real-players

### obtener un registro de RealPlayer por id
GET http://127.0.0.1:3000/api/real-players/1

### crear un nuevo registro de RealPlayer
POST http://127.0.0.1:3000/api/real-players
Content-Type: application/json

{
  "idEnApi": "1",
  "name": "Liga Profesional",
  "position": "forward",
  "realTeamId": "1",
  "valueCurrency": "ARS",
  "value": 5500000,
  "active": true
}

### actualizar un registro de RealPlayer por id
PUT http://127.0.0.1:3000/api/real-players/1
Content-Type: application/json

{
  "idEnApi": "1",
  "name": "Liga Profesional actualizado",
  "position": "midfielder",
  "realTeamId": "1",
  "valueCurrency": "USD",
  "value": 1200000,
  "active": true
}

### actualizar parcialmente un registro de RealPlayer por id
PATCH http://127.0.0.1:3000/api/real-players/1
Content-Type: application/json

{
  "idEnApi": "1",
  "name": "Liga Profesional actualizado",
  "position": "midfielder",
  "valueCurrency": "EUR",
  "value": 1350000
}

### eliminar un registro de RealPlayer por id
DELETE http://127.0.0.1:3000/api/real-players/1

### buscar por idEnApi
GET http://127.0.0.1:3000/api/real-players/by-id-en-api/1


### sincronizar jugadores por leagueIdEnApi
POST http://127.0.0.1:3000/api/real-players/sync/by-league-id-en-api
Content-Type: application/json

{
  "leagueIdEnApi": 72
}

### actualizar plantilla de un equipo por teamIdEnApi
POST http://127.0.0.1:3000/api/real-players/sync/team-squad
Content-Type: application/json

{
  "teamIdEnApi": 9050
}
