### obtener todos los usuarios
GET http://127.0.0.1:3000/api/users

### obtener un registro de User por id
GET http://127.0.0.1:3000/api/users/1

### crear un nuevo registro de User
POST http://127.0.0.1:3000/api/users
Content-Type: application/json

{
  "username": "juanperez",
  "password": "ClaveSegura123!",
  "mail": "juan.perez@example.com"
}

### actualizar un registro de User por id
PUT http://127.0.0.1:3000/api/users/1
Content-Type: application/json

{
  "username": "nperez",
  "password": "ClaveSegura123!",
  "mail": "juan.perez@example.com"
}

### actualizar parcialmente un registro de User por id
PATCH http://127.0.0.1:3000/api/users/3
Content-Type: application/json

{
  "mail": "juan.ez@example.com"
}

### eliminar un registro de User por id
DELETE http://127.0.0.1:3000/api/users/1
