### obtener todos los registros de Negotiation
GET http://127.0.0.1:3000/api/negotiations

### obtener un registro de Negotiation por id
GET http://127.0.0.1:3000/api/negotiations/1

### crear un nuevo registro de Negotiation
POST http://127.0.0.1:3000/api/negotiations
Content-Type: application/json

{
  "tournamentId": "1",
  "sellerParticipantId": "1",
  "buyerParticipantId": "1",
  "dependantPlayerId": "1",
  "agreedAmount": 3200000,
  "status": "active",
  "publicationDate": "2026-02-10T12:00:00.000Z",
  "effectiveDate": "2026-02-11T12:00:00.000Z",
  "rejectionDate": "2026-02-20T12:00:00.000Z"
}

### actualizar un registro de Negotiation por id
PUT http://127.0.0.1:3000/api/negotiations/1
Content-Type: application/json

{
  "tournamentId": "1",
  "sellerParticipantId": "1",
  "buyerParticipantId": "1",
  "dependantPlayerId": "1",
  "agreedAmount": 3200100,
  "status": "accepted",
  "publicationDate": "2026-02-10T12:00:00.000Z",
  "effectiveDate": "2026-02-11T12:00:00.000Z",
  "rejectionDate": "2026-02-20T12:00:00.000Z"
}

### actualizar parcialmente un registro de Negotiation por id
PATCH http://127.0.0.1:3000/api/negotiations/1
Content-Type: application/json

{
  "tournamentId": "1",
  "sellerParticipantId": "1",
  "buyerParticipantId": "1",
  "status": "accepted"
}

### eliminar un registro de Negotiation por id
DELETE http://127.0.0.1:3000/api/negotiations/1
